[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerfileTarget = "production"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "gunicorn contexts.wsgi:application --bind 0.0.0.0:8002 --workers 2 --timeout 120 --log-level debug"