[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerfileTarget = "production"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python manage.py migrate --noinput && gunicorn assets.wsgi:application --bind 0.0.0.0:${PORT:-8002} --workers 2 --timeout 120 --log-level debug"
