[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerfileTarget = "production"

[deploy]
startCommand = "caddy run --config Caddyfile --adapter caddyfile"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 300

