[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
dockerfileTarget = "production"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python manage.py migrate --noinput && gunicorn contexts.wsgi:application --bind 0.0.0.0:$PORT --log-level debug"