[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/authentication/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python manage.py migrate --noinput && gunicorn authentication.wsgi:application --bind 0.0.0.0:$PORT"
